http_response_headers.settings:
  type: config_object
  mapping:
    allowed_headers:
      type: text
      label: 'Allowed headers'
    exclude_pages:
      type: sequence
      label: 'Exclude Pages'
      sequence:
        type: string
